### ISSUE TITLE
REGEXP role does not have token

### ISSUE THREAD

**Issue by zurk** [bblfsh/javascript-driver#37] opened 2018-09-30 14:52 UTC
if you parse next js code
```js
x = /<regexp>/;
```
you have next UAST tree:
```
#           Token  Internal Role         Roles Tree                                                    
                                                                                                       
(1, 1, 13)  ||     File                  FILE                                                          
(1, 1, 13)  ||     Program               ┣ MODULE                                                      
(1, 1, 13)  ||     ExpressionStatement   ┃ ┣ STATEMENT                                                 
(1, 1, 13)  ||     AssignmentExpression  ┃ ┃ ┣ EXPRESSION, ASSIGNMENT, OPERATOR, BINARY                
(1, 1, 2)   |x|    Identifier            ┃ ┃ ┃ ┣ EXPRESSION, IDENTIFIER, ASSIGNMENT, BINARY, LEFT      
(1, 3, 13)  ||     RegExpLiteral         ┗ ┗ ┗ ┗ EXPRESSION, LITERAL, REGEXP, ASSIGNMENT, BINARY, RIGHT
```

and there is no token for `RegExpLiteral` Node. I think it is because it stored not in `value`, but in `pattern` field: https://github.com/babel/babylon/blob/master/ast/spec.md#regexpliteral .

It should be easy to fix.

**Comment by EgorBu** [comment] 2018-10-01 13:52
Duplicate of https://github.com/bblfsh/javascript-driver/issues/22

**Comment by dennwc** [comment] 2018-10-17 12:43
Cannot reproduce this with the latest driver

**Closed by dennwc** 2018-10-17 12:43 UTC
Labels: bug
